// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package oppgave1

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Oppgave1Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"root\" x-data=\"{count: 0, clickEvt: 0}\" x-init=\"let FetchVisitCount =  async function() {\r\n    const xAPIKEY = 'f414d481-8f7b-41e5-ab5e-05814bb1f509';\r\n    try {\r\n      const response = await fetch('http://localhost:8081/oppgave1/rng/generateNumber', {\r\n        method: 'GET',\r\n        headers: { 'X-API-KEY': xAPIKEY }\r\n      });\r\n      const data = await response.json();\r\n      return data.visitors;\r\n    } catch (error) {\r\n      console.error('Error fetching visitor count:', error);\r\n      return 0;\r\n    }\r\n  };\r\n  count = await FetchVisitCount();\r\n  $watch('clickEvt', value => {count = FetchVisitCount()})\r\n  \" class=\"flex flex-col items-center justify-center bg-gray-100 w-full flex-grow\"><!-- Visitor counter and title --><div class=\"flex flex-col items-center justify-center space-y-4 pt-4\"><!-- Title --><div class=\"text-center\"><h1 class=\"text-2xl font-semibold text-gray-800\">Random Number Generator</h1></div><!-- Counter Display --><div class=\"text-center\"><div x-text=\"count\" class=\"text-9xl pb-4 font-extrabold text-black-500\" x-transition:enter=\"transition ease-out duration-700\" x-transition:enter-start=\"opacity-0 transform scale-90\" x-transition:enter-end=\"opacity-100 transform scale-100\"><!-- Counter value --></div><button class=\"bg-white shadow rounded p-2\" @click=\"clickEvt += 1;\">Nytt tall</button></div></div></div><!-- API Button, positioned at the bottom --><div class=\"w-full px-4 py-2 flex justify-center\"><button hx-get=\"/oppgave1/openapi\" hx-push-url=\"true\" hx-swap=\"outerHTML\" hx-target=\"#root\" class=\"bg-blue-500 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded\">View API Documentation</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func OpenAPIPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div id=\"root\" class=\"h-full w-full flex\"><!-- Elements API and styles are moved here --><script src=\"https://unpkg.com/@stoplight/elements/web-components.min.js\"></script><link rel=\"stylesheet\" href=\"https://unpkg.com/@stoplight/elements/styles.min.css\"><!-- Elements API and styles are included here --><elements-api id=\"openapi\" apiDescriptionUrl=\"http://localhost:8081/oppgave1/openapi.yaml\" router=\"hash\" layout=\"sidebar\" class=\"flex-grow\"></elements-api></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
