// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package Oppgave6

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Oppgave6HintPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"root\" class=\"flex flex-col justify-center items-center px-4 sm:px-6 lg:px-8\"><div class=\"max-w-md w-full space-y-8 break-words\">RW4gZ2FuZyBpIGVuIGxpdGVuIGJ5LCBib2RkZSBkZXQgZW4gbWFubiB2ZWQgbmF2biBCZXJudC4gQmVybnQgdmFyIGVuIGthcnRvZ3JhZiwgZW4gc29tIGxhZ2VyIGthcnQuIEhhbiBoYWRkZSBlbiBsaWRlbnNrYXAgZm9yIGRldGFsamVyIG9nIG7DuHlha3RpZ2hldCwgb2cgaGFuIGJydWt0ZSBkYWdlbmUgc2luZSBww6Ugw6UgdGVnbmUga2FydCBvdmVyIGJ5ZW4gc2luIG9nIG9tcsOlZGVuZSBydW5kdC4KCkVuIGRhZyBiZXN0ZW10ZSBCZXJudCBzZWcgZm9yIMOlIGxhZ2UgZXQgbnl0dCBrYXJ0LiBIYW4gYmVneW50ZSBtZWQgw6Ugc2tpc3NlcmUgZGUgc3RvcmUgbGluamVuZTogYnllbnMgZ3JlbnNlciwgZGUgdmlrdGlnc3RlIHZlaWVuZSwgZWx2ZW4gc29tIGzDuHAgZ2plbm5vbSBzZW50cnVtLiBIYW4gYnJ1a3RlIGVuIGZpbiBwZW5zZWwgZm9yIMOlIHRlZ25lIGh2ZXIgZW5lc3RlIGxpbGxlIGRldGFsajogaHZlcnQgaHVzLCBodmVyIHBhcmssIGh2ZXIgYnJvLgoKRXR0ZXIgZmxlcmUgZGFnZXIgbWVkIGFyYmVpZCwgdmFyIGthcnRldCBuZXN0ZW4gZmVyZGlnLiBNZW4gQmVybnQgZsO4bHRlIGF0IG5vZSBtYW5nbGV0LiBIYW4gYmVzdGVtdGUgc2VnIGZvciDDpSBsZWdnZSB0aWwgZXQgZmxhZ2cgcMOlIGthcnRldC4gRGV0dGUgZmxhZ2dldCBza3VsbGUgcmVwcmVzZW50ZXJlIGJ5ZW5zIHLDpWRodXMsIGJ5ZW5zIGhqZXJ0ZSBvZyBzamVsLgoKQmVybnQgdmFsZ3RlIGVuIGx5cyBibMOlIGZhcmdlIGZvciBmbGFnZ2V0LCBlbiBmYXJnZSBzb20gc2t1bGxlIHJlcHJlc2VudGVyZSBieWVucyBsaXYgb2cgZW5lcmdpLiBIYW4gcGxhc3NlcnRlIGZsYWdnZXQgbsO4eWUgcMOlIGthcnRldCwgYWtrdXJhdCBkZXIgcsOlZGh1c2V0IHN0by4gSGFuIHN0dWRlcnRlIGFyYmVpZGV0IHNpdHQgbsO4eWUsIG9nIHRpbCBzbHV0dCBuaWtrZXQgaGFuIGZvcm7DuHlkLiBLYXJ0ZXQgdmFyIG7DpSBrb21wbGV0dC4KCk9nIHNsaWsgZ2lrayBkYWdlbmUgZm9yIEJlcm50LCBkYWcgdXQgb2cgZGFnIGlubi4gSGFuIHRlZ25ldCBrYXJ0LCBsYSB0aWwgZGV0YWxqZXIsIHBsYXNzZXJ0ZSBmbGFnZy4gRGV0IHZhciBldCByb2xpZyBsaXYsIG1lbiBCZXJudCB2YXIgZm9ybsO4eWQuIEhhbiB2aXNzdGUgYXQgaGFuIGdqb3JkZSBldCB2aWt0aWcgYXJiZWlkLCBvZyBoYW4gZWxza2V0IGh2ZXJ0IMO4eWVibGlrayBhdiBkZXQuCgpPZyBmbGFnZ2V0IGZvciBkZW5uZSBoaXN0b3JpZW4gZXIgImZsYWd7czNjcjN0XzNuYzBkMW5nfSIu</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
